config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  get 'welcome/show'
  get 'kelas/index'
  get 'mahasiswa/index'

  patch 'welcome/:id/edit', controller: 'welcome', action: :update

  devise_for :users

  resources :welcome
  
  resources :kelas do
  	resources :mahasiswa_join_kelas 
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role == "Admin"
        can :manage, :all
    elsif user.role == "Dosen"
        can :read, :all
        can [:read, :create]
    elsif user.role == "Mahasiswa"
        can :read, :all
        can [:read, :create]
        
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kela.rb
class Kela < ApplicationRecord
	has_many :mahasiswa_join_kelas, dependent: :destroy
end

app/models/mahasiswa_join_kela.rb
class MahasiswaJoinKela < ApplicationRecord
	belongs_to :kela
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def active_for_authentication?
  	if role == "Admin" || status == "approved"
  		super
  	end
  end

  def inactive_message
  	if status == "pending" || role != "Admin"
  		:not_approved
  	else
  		super
  	end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!

  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to root_url, :alert => exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
  		user_params.permit(:email, :password, :password_confirmation, :role, :nama, :gender, :b_date, :alamat, :kota, :no_telp, :status)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:email, :role, :nama, :gender, :b_date, :alamat, :kota, :no_telp, :current_password)
    end
  
  end
end

app/controllers/kelas_controller.rb
class KelasController < ApplicationController

	def new
		@kela = Kela.new
	end

	def create
	  @kela = Kela.new(kela_params)
	 
	  if @kela.save
	  	 redirect_to kelas_path
	  else
	  	 render 'index'
	  end
	end

	def edit
		@kela = Kela.find(params[:id])
	end

	def update
		@kela = Kela.find(params[:id])

		if @kela.update(kela_params)
			redirect_to kelas_path
		else
			render 'edit'
		end
	end


	def destroy
		@kela = Kela.find(params[:id])
		@kela.destroy

		redirect_to kelas_path
	end


	def show
		@kela = Kela.find(params[:id])
	end

	def index
		@kelas = Kela.all
		@mhs_join = MahasiswaJoinKela.all
	end

	 
	private

	  def kela_params
	    params.require(:kela).permit(:nama_mk, :kode_mk, :waktu, :jumlah_mhs, :ruang)
	  end
end

app/controllers/mahasiswa_join_kelas_controller.rb
class MahasiswaJoinKelasController < ApplicationController
	def new
		@mahasiswa_join_kela = Mahasiswa_join_kela.new
	end

	def create
	  @kela = Kela.find(params[:kela_id])
	  @mahasiswa_join_kela = @kela.mahasiswa_join_kelas.create(mhsw_join_params)
	  redirect_to kelas_path
	end

	def update
		@mahasiswa_join_kela = MahasiswaJoinKela.find(params[:id])

		if @mahasiswa_join_kela.update(mhsw_join_params)
			redirect_to kelas_path
		end
	end

	def index
		@mahasiswa_join_kelas = Mahasiswa_join_kela.all
	end


	private
	def mhsw_join_params
		params.require(:mahasiswa_join_kela).permit(:matakuliah, :mahasiswa_join, :status)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@kelas = Kela.all

  end

  def show
  	if params[:role] == "mahasiswa"
  		@users = User.where(role: "mahasiswa")
  	elsif params[:role] == "dosen"
  		@users = User.where(role: "dosen")
  	else
  		@users = User.all
  	end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])

  	if @user.update(user_params)
  		redirect_to welcome_show_path
  	end
  end

private
	def user_params
		params.require(:user).permit(:status)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kelas_helper.rb
module KelasHelper
end

app/helpers/mahasiswa_join_helper.rb
module MahasiswaJoinHelper
end

app/helpers/mahasiswa_join_kelas_helper.rb
module MahasiswaJoinKelasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/kelas/edit.html.erb
<div class="box">
<%= form_for @kela do |f| %>
	
	<% if @kela.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@kela.errors.count, "error") %> prohibited this article from being saved :
			</h2>
			<ul>
				<% @kela.errors.full_messages.each do |msg| %>
				  <li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<form>
      <div class="mui-textfield">
        <%= f.text_field :nama_mk %>
        <label>Nama Mata Kuliah</label>
      </div>
      <div class="mui-textfield">
        <%= f.text_field :kode_mk %>
        <label>Nama Mata Kuliah</label>
      </div>
      <div class="mui-textfield">
        <%= f.text_field :waktu %>
        <label>Nama Mata Kuliah</label>
      </div>
      <div class="mui-textfield">
        <%= f.text_field :jumlah_mhs %>
        <label>Nama Mata Kuliah</label>
      </div>
      <div class="mui-textfield">
        <%= f.text_field :ruang %>
        <label>Nama Mata Kuliah</label>
      </div>
      <div class="buttonMid"> 
 		<p><button type="submit" class="mui-btn mui-btn--raised">Update Kelas</button></p>
 	  </div>	
	</form>
<% end %>
<div class="buttonMid"> 
	<p>
		<%= link_to 'Back', kelas_index_path, :style=>"width:84%", :class=>"mui-btn mui-btn--raised mui-btn--danger" %>
	</p>
</div>
</div>

app/views/kelas/index.html.erb
<% if current_user.role == "Dosen" %>
  <%= form_for :kela, url: kelas_path do |f| %>
    <div class="box-mataKuliah">
      <form>
          <div class="mui-textfield">
            <%= f.text_field :nama_mk, autofocus: true %>
            <label>Nama Mata Kuliah</label>
          </div>

          <div class="mui-textfield">
            <%= f.text_field :kode_mk, autofocus: true %>
            <label>Kode Mata Kuliah</label>
          </div>

          <div class="mui-textfield">
            <%= f.text_field :waktu, autofocus: true %>
            <label>Waktu</label>
          </div>

          <div class="mui-textfield">
            <%= f.text_field :jumlah_mhs, autofocus: true %>
            <label>Jumlah Mahasiswa</label>
          </div>

          <div class="mui-textfield">
            <%= f.text_field :ruang, autofocus: true %>
            <label>Ruang</label>
          </div>

          <button type="submit" class="mui-btn mui-btn--raised mui-btn--primary">Tambah</button>
      </form>
    </div>
  <% end %>

  <div class="box-tabelMataKuliah">
    <table class="table table-striped">
      <tr>
        <th>Nama Mata Kuliah</th>
        <th>Kode Mata Kuliah</th>
        <th>Waktu</th>
        <th>Jumlah Mahasiswa</th>
        <th>Ruang</th>
        <th colspan="3"></th>
      </tr>

      <% @kelas.each do |kela| %>
        <tr>
          <td><%= kela.nama_mk %></td>
          <td><%= kela.kode_mk %></td>
          <td><%= kela.waktu %></td>
          <td><%= kela.jumlah_mhs %></td>
          <td><%= kela.ruang %></td>
          <td><%= link_to 'Edit', edit_kela_path(kela), { :class=>"mui-btn mui-btn--raised" } %></td>
          <td><%= link_to 'Show', kela_path(kela), { :class=>"mui-btn mui-btn--raised" }  %></td>
          <td><%= link_to 'Destroy', kela_path(kela),
              method: :delete,
              data: { confirm: 'Are you sure?' }, :class=>"mui-btn mui-btn--raised mui-btn--danger"  %></td>
        </tr>
      <% end %>
    </table>
    <p>
      <%= link_to 'Back', welcome_index_path, {  :class=>"mui-btn mui-btn--raised mui-btn--primary" } %>
    </p>
  </div>


<% elsif current_user.role == "Mahasiswa" %>
<div class="box-signup">
  <table class="table table-striped">
    <tr>
      <th>Nama Mata Kuliah</th>
      <th>Waktu</th>
      <th colspan="3"></th>
    </tr>

    <% @kelas.each do |k| %>
      <tr>
        <td><%= k.nama_mk %></td>
        <td><%= k.waktu %></td>
        <td><%= link_to 'Join', kela_path(k), :class=>"mui-btn mui-btn--raised mui-btn--primary" %></td>
      </tr>
    <% end %>

  </table>
  <p>
    <%= link_to 'Back', welcome_index_path, :class=>"mui-btn mui-btn--raised mui-btn--danger" %>
  </p>
</div>
<% end %>

app/views/kelas/show.html.erb
<% if current_user.role == "Dosen" %>
	<div class="box-signup">
		<p>
			<strong>Nama Matakuliah :</strong>
				<%= @kela.nama_mk %>
		</p>
		<p>
			<strong>Kode Matakuliah :</strong>
				<%= @kela.kode_mk %>
		</p>

		<table class="table table-bordered">
			<tr>
				<th>Mahasiswa</th>
				<th>Status</th>
				<th>Action</th>
			</tr>
			<% @kela.mahasiswa_join_kelas.each do |join| %>
		        <tr>
		          <td><%= join.mahasiswa_join %></td>
		          <td><%= join.status %></td>
		          <td>
	          		<%= form_for ([@kela, join]) do |f| %>
	          			<%= f.hidden_field :status, :value => "approved" %>
	          			<%= f.submit 'Approve' %>
	          		<% end %>
		          </td>
		        </tr>
	      <% end %>
		</table>

		<%= link_to 'Back', kelas_index_path, :class=>"mui-btn mui-btn--raised mui-btn--danger" %>
	</div>

<% elsif current_user.role == "Mahasiswa" %>
	<div class="box">
		<p>
			<strong>Nama Matakuliah :</strong>
				<%= @kela.nama_mk %>
		</p>

		<p>
			<strong>Kode Matakuliah :</strong>
				<%= @kela.kode_mk %>
		</p>

		<p>
			<strong>Waktu :</strong>
				<%= @kela.waktu %>
		</p>
		<p>
			<strong>Ruang :</strong>
				<%= @kela.ruang %>
		</p>

		<p>
			<%= form_for ([@kela, @kela.mahasiswa_join_kelas.build]) do |f| %>
				<%= f.hidden_field :matakuliah, :value => @kela.nama_mk %>
				<%= f.hidden_field :mahasiswa_join, :value => current_user.email %>
				<%= f.hidden_field :status, :value => "pending" %>
				<%= f.submit 'Join' , :class=>"mui-btn mui-btn--raised mui-btn--primary" %>
			<% end %>
			
			<!--<%= render 'mahasiswa_join_kelas/hiddendaftar' %> -->

		</p>
		<%= link_to 'Back', kelas_index_path, :class=>"mui-btn mui-btn--raised mui-btn--danger" %>
	</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UcWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="//cdn.muicss.com/mui-0.9.4/css/mui.min.css" rel="stylesheet" type="text/css" />
    <script src="//cdn.muicss.com/mui-0.9.4/js/mui.min.js"></script>

    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
  </head>

  <body>   
     <!-- <div>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
     </div> -->

    <%= yield %>
  </body>
</html>

app/views/mahasiswa_join_kelas/_hiddendaftar.html.erb
<!--
<%= form_for ([@kela, @kela.mahasiswa_join_kelas.build]) do |f| %>
	<%= f.hidden_field :matakuliah, :value => @kela.nama_mk %>
	<%= f.hidden_field :mahasiswa_join, :value => current_user.email %>
	<%= f.submit 'Join' %>
	
<% end %>
-->

app/views/welcome/edit.html.erb
<div class="box-approve">
	Approve sekarang?
	<%= form_for :user, method: :patch do |f| %>
		<%= f.hidden_field :status, :value => "approved"%>
		<button type="submit" class="mui-btn mui-btn--raised">Approve</button>
		<%= link_to 'Back', welcome_index_path, :style=>"width:39%", :class=>"mui-btn mui-btn--raised mui-btn--danger" %>
	<% end %>
</div>

app/views/welcome/index.html.erb
<% if current_user.role == "Dosen" %>
	<div class="box-signup">
  		<div class="leftFormProfile">
			<h2>PROFILE</h2>
			<%= link_to 'Mata Kuliah', kelas_index_path, { :style=>"width:84%", :class=>"mui-btn mui-btn--raised"} %> <br/>
			<%= link_to 'Edit Profile', edit_user_registration_path, { :class=>"mui-btn mui-btn--raised" } %>

			<p>
				<%= link_to 'Log Out', destroy_user_session_path,
				method: :delete,
				data: {confirm: 'Are you sure?'}, :style=>"width:84%", :class=>"mui-btn mui-btn--raised mui-btn--primary" %> </br>
			</p>
		</div>
		<div class="rightForm">

			<i class="fa fa-user" aria-hidden="true"></i> <b>Nama</b><br/>
			<%= current_user.nama %><br/><br>

			<i class="fa fa-venus-mars" aria-hidden="true"></i> <b>Gender</b><br>
			<%= current_user.gender %> <br/><br>

			<i class="fa fa-birthday-cake" aria-hidden="true"></i> <b>Tanggal lahir</b><br>
			<%= current_user.b_date%> <br/><br>

			<i class="fa fa-home" aria-hidden="true"></i> <b>Alamat</b><br>
			<%= current_user.alamat %>, <%= current_user.kota %> <br/><br>

			<i class="fa fa-mobile" aria-hidden="true"></i> <b>No Telepon</b><br>
			<%= current_user.no_telp %> <br/><br>

			<i class="fa fa-envelope" aria-hidden="true"></i> <b>Email</b><br>
			<%= current_user.email %> <br/>	<br>		
		</div>
	</div>

<% elsif current_user.role == "Mahasiswa" %>
	<div class="box-signup">
  		<div class="leftFormProfile">
  			<h2>PROFILE</h2>
			<%= link_to 'Join kelas', kelas_index_path, { :style=>"width:84%", :class=>"mui-btn mui-btn--raised" }%><br/>
			<%= link_to 'Edit Profile', edit_user_registration_path, { :class=>"mui-btn mui-btn--raised" }%>

			<p>
				<%= link_to 'Log Out', destroy_user_session_path,
				method: :delete,
				data: {confirm: 'Are you sure?'}, :style=>"width:84%", :class=>"mui-btn mui-btn--raised mui-btn--primary" %> </br>
			</p>
		</div>
		<div class="rightForm">

			<i class="fa fa-user" aria-hidden="true"></i> <b>Nama</b><br/>
			<%= current_user.nama %><br/><br>

			<i class="fa fa-venus-mars" aria-hidden="true"></i> <b>Gender</b><br>
			<%= current_user.gender %> <br/><br>

			<i class="fa fa-birthday-cake" aria-hidden="true"></i> <b>Tanggal lahir</b><br>
			<%= current_user.b_date%> <br/><br>

			<i class="fa fa-home" aria-hidden="true"></i> <b>Alamat</b><br>
			<%= current_user.alamat %>, <%= current_user.kota %> <br/><br>

			<i class="fa fa-mobile" aria-hidden="true"></i> <b>No Telepon</b><br>
			<%= current_user.no_telp %> <br/><br>

			<i class="fa fa-envelope" aria-hidden="true"></i> <b>Email</b><br>
			<%= current_user.email %> <br/>	<br>		
		</div>
	</div>
	

<% elsif current_user.role == "Admin" %>
	<div class="box-signup">
  		<div class="leftFormProfile">
  			<h2>PROFILE</h2>
			<%= link_to 'Edit Profile', edit_user_registration_path, { :style=>"width:84%", :class=>"mui-btn mui-btn--raised" } %></br>
			<%= link_to 'Manage User', welcome_show_path, { :style=>"width:84%", :class=>"mui-btn mui-btn--raised" } %> 

			<p>
				<%= link_to 'Log Out', destroy_user_session_path,
				method: :delete,
				data: {confirm: 'Are you sure?'}, :style=>"width:84%", :class=>"mui-btn mui-btn--raised mui-btn--primary" %> </br>
			</p>
		</div>
		<div class="rightForm">

			<i class="fa fa-user" aria-hidden="true"></i> <b>Nama</b><br/>
			<%= current_user.nama %><br/><br>

			<i class="fa fa-venus-mars" aria-hidden="true"></i> <b>Gender</b><br>
			<%= current_user.gender %> <br/><br>

			<i class="fa fa-birthday-cake" aria-hidden="true"></i> <b>Tanggal lahir</b><br>
			<%= current_user.b_date%> <br/><br>

			<i class="fa fa-home" aria-hidden="true"></i> <b>Alamat</b><br>
			<%= current_user.alamat %>, <%= current_user.kota %> <br/><br>

			<i class="fa fa-mobile" aria-hidden="true"></i> <b>No Telepon</b><br>
			<%= current_user.no_telp %> <br/><br>

			<i class="fa fa-envelope" aria-hidden="true"></i> <b>Email</b><br>
			<%= current_user.email %> <br/>	<br>		
		</div>
	</div>
<% end %>

app/views/welcome/show.html.erb
<%= link_to "Semua", :action => "show", :class=>"mui-btn mui-btn--raised"%> |
<%= link_to "Mahasiswa", :action => "show", :role => "mahasiswa" %> |
<%= link_to "Dosen", :action => "show", :role => "dosen" %>

<table class="table table-bordered">
	<tr>
		<th>Mahasiswa</th>
		<th>Status</th>
		<th>Action</th>
	</tr>>

	<% @users.each do |log| %>
	<tr>
		<td><%= log.email %></td>
		<td><%= log.status %></td>
		<td>
      		<%= link_to 'approve', edit_welcome_path(log), :class=>"mui-btn mui-btn--raised mui-btn--primary"  %>
      	</td>
	</tr>

	<% end %>

</table>

<p><%= link_to 'Back', welcome_index_path, :class=>"mui-btn mui-btn--raised mui-btn--danger"  %></p>